# Generated by Django 5.1.1 on 2025-04-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rating_rating_value_validate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workshoprepair',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='validated_latitude', violation_error_message='Invalid Latitude'),
        ),
        migrations.AddConstraint(
            model_name='workshoprepair',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='validated_longitude', violation_error_message='Invalid Longitude'),
        ),
    ]
